#!/bin/bash

source ../bin/config-shared.bash

# Script: cc-js
# Runs a CodeceptJs command.

if [ ! -d ../node_modules ] || [ ! -e ../node_modules/.bin/codeceptjs ]; then
  show_fail "Please set up the test environment with install-wp-tests.sh"
fi

_script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

# shellcheck disable=SC2048
(cd "$_script_dir" && ../node_modules/.bin/codeceptjs $*)
