#!/bin/bash

source ../bin/config-shared.bash

QA_STARTTIME=$(date +%s)

{ # try
  _script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

  # shellcheck disable=SC2048
  (cd "$_script_dir" && npx codeceptjs run --config ./_config/codecept.js --steps --grep $*)
} || { #catch
  echo 'Error with run. Inspect output in _output directory'
}

if [[ -z $CC_SILENT ]]; then
  QA_ENDTIME=$(date +%s)
  echo "It took $(($QA_ENDTIME - $QA_STARTTIME)) seconds to complete."

  separator
  echo 'Tests were run with command:'

  # shellcheck disable=SC2048
  echo npx codeceptjs run --config ./_config/codecept.js --steps --grep $*
fi
